// apps/web/app/pages/about.vue
<script setup lang="ts">
import type { About } from '@machi11/types'
import { usePayload } from '~/composables/usePayload'
import { useRichText } from '~/composables/useRichText'

const { getGlobals, getImageUrl } = usePayload()
const { serialize } = useRichText()
const { ui } = useI18n()
const { data: about } = await useAsyncData('about', () => getGlobals('about'))

// SEO Metadata
useSeoMeta({
  title: about.value?.meta?.title || `À propos - ${about.value?.name || 'Mama Couture'}`,
  ogTitle: about.value?.meta?.title || about.value?.name,
  description: about.value?.meta?.description || 'Découvrez l\'histoire et les créations de Mama Couture.',
  ogDescription: about.value?.meta?.description,
  ogImage: about.value?.meta?.image ? getImageUrl(about.value.meta.image) : (about.value?.profileImage ? getImageUrl(about.value.profileImage) : ''),
  twitterCard: 'summary_large_image',
})
</script>

<template>
  <div class="py-4 md:py-10 container mx-auto px-6">
    <div class="grid grid-cols-1 md:grid-cols-2 gap-8 md:gap-12 lg:gap-20 items-start md:items-center">
      <!-- Image Section -->
      <div class="relative w-full max-w-xl mx-auto aspect-square bg-secondary/50 overflow-hidden rounded-sm border border-primary/5 shadow-lg">
        <div class="absolute inset-0 bg-accent/5 z-10"></div>
        <!-- Profile Image Placeholder -->
        <NuxtImg 
          v-if="about?.profileImage"
          :src="getImageUrl(about.profileImage)"
          :alt="ui.about.imageAlt"
          class="w-full h-full object-cover transition-transform duration-1000 hover:scale-105"
        />
        <div v-else class="w-full h-full flex items-center justify-center text-primary/20 bg-secondary">
          <span class="font-serif italic text-lg">{{ ui.about.imageAlt }}</span>
        </div>
      </div>
      
      <!-- Content Section -->
      <div class="flex flex-col">
        <h2 class="text-accent text-sm uppercase tracking-[0.2em] mb-2 font-semibold flex items-center gap-4">
          <span class="w-8 h-[1px] bg-accent"></span>
          {{ ui.about.badge }}
        </h2>
        
        <h1 class="text-4xl lg:text-5xl font-serif mb-6 text-primary leading-tight">
          {{ about?.name || ui.about.defaultTitle }}
        </h1>
        
        <div class="prose prose-lg text-primary/80 font-light leading-relaxed mb-4 md:mb-6 max-w-none">
          <p v-if="!about">{{ ui.common.loading }}</p>
          <div v-else>
            <!-- If bio is a string (rich text HTML) -->
            <div v-if="typeof about.bio === 'string'" v-html="about.bio"></div>
            <!-- If bio is a Lexical object -->
            <div v-else-if="about.bio" v-html="serialize(about.bio)"></div>
          </div>
        </div>
        
        <div class="border-t border-primary/10 pt-4 md:pt-6 mt-4 md:mt-6 bg-primary/5 p-4 md:p-6 rounded-sm">
          <h4 class="font-serif text-2xl italic text-primary mb-4 flex items-center gap-3">
             <span class="w-6 h-[1px] bg-accent"></span>
             <span>{{ ui.common.contactTitle }}</span>
          </h4>
          
          <div class="flex flex-col gap-4">
             <!-- Email -->
             <a :href="`mailto:${about?.contactEmail}`" class="group flex items-center gap-4 text-primary/80 hover:text-accent transition-all duration-300">
               <div class="w-10 h-10 rounded-full border border-primary/20 flex items-center justify-center group-hover:border-accent group-hover:bg-accent/5 transition-colors">
                 <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                   <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M3 8l7.89 5.26a2 2 0 002.22 0L21 8M5 19h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z" />
                 </svg>
               </div>
               <span class="font-medium tracking-wide text-lg pb-0.5 border-b border-transparent group-hover:border-accent">{{ about?.contactEmail }}</span>
             </a>

             <!-- Social Networks -->
             <div v-if="about?.socialLinks?.length" class="flex flex-wrap gap-4 mt-2">
                <a v-for="social in about?.socialLinks" :key="social.platform" :href="social.url" target="_blank" 
                   class="group flex items-center gap-3 px-5 py-3 bg-secondary/50 backdrop-blur-sm border border-primary/10 rounded-sm hover:border-accent/50 hover:shadow-md transition-all duration-300 transform hover:-translate-y-0.5"
                >
                  <!-- Icon based on platform name (simple check) -->
                  <svg v-if="social.platform.toLowerCase().includes('instagram')" xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 text-accent" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="2" y="2" width="20" height="20" rx="5" ry="5"></rect><path d="M16 11.37A4 4 0 1 1 12.63 8 4 4 0 0 1 16 11.37z"></path><line x1="17.5" y1="6.5" x2="17.51" y2="6.5"></line></svg>
                  <svg v-else-if="social.platform.toLowerCase().includes('facebook')" xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 text-accent" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M18 2h-3a5 5 0 0 0-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 0 1 1-1h3z"></path></svg>
                  <svg v-else xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 text-accent" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 12a9 9 0 11-18 0 9 9 0 0118 0z" /><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3.6 9h4.9a8 8 0 010 9v0a8 8 0 01-4.9-3" /><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M20.4 9h-4.9a8 8 0 000 9v0a8 0 004.9-3" /></svg>
                  
                  <span class="uppercase text-xs font-bold tracking-widest text-primary/80 group-hover:text-primary">{{ social.platform }}</span>
                </a>
             </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

// apps/cms/src/app/(frontend)/about/page.tsx
import React from 'react'
import { getPayload } from 'payload'
import config from '@/payload.config'
import Image from 'next/image'
import { Mail, Instagram, Facebook, Link as LinkIcon } from 'lucide-react'
import { Header } from '@/components/layout/Header'
import { Footer } from '@/components/layout/Footer'
import { RichText } from '@/components/shared/RichText'
import { SiteSetting, UiString, About as AboutType } from '@/payload-types'

export default async function AboutPage() {
  const payload = await getPayload({ config })

  const siteSettings = await payload.findGlobal({ slug: 'site-settings' }) as unknown as SiteSetting
  const uiStrings = await payload.findGlobal({ slug: 'ui-strings' }) as unknown as UiString
  const about = await payload.findGlobal({ slug: 'about' }) as unknown as AboutType

  const profileImageUrl = typeof about.profileImage === 'object' ? about.profileImage?.url : null

  return (
    <div className="flex flex-col min-h-screen">
      <Header 
        siteTitle={siteSettings.siteTitle} 
        navStrings={{
          collections: uiStrings.nav?.collections || 'Collections',
          about: uiStrings.nav?.about || 'À propos',
          contact: uiStrings.nav?.contact || 'Contact',
          menuLabel: uiStrings.nav?.menuLabel || 'Menu',
        }}
        socialLinks={about.socialLinks || []}
      />

      <main className="flex-grow py-4 md:py-10 container mx-auto px-6">
        <div className="grid grid-cols-1 md:grid-cols-2 gap-8 md:gap-12 lg:gap-20 items-start md:items-center">
          {/* Image Section */}
          <div className="relative w-full max-w-xl mx-auto aspect-square bg-secondary/50 overflow-hidden rounded-sm border border-primary/5 shadow-lg">
            <div className="absolute inset-0 bg-accent/5 z-10" />
            {profileImageUrl ? (
              <Image
                src={profileImageUrl}
                alt={uiStrings.about?.imageAlt || 'About Mama Couture'}
                fill
                className="object-cover transition-transform duration-1000 hover:scale-105"
              />
            ) : (
              <div className="w-full h-full flex items-center justify-center text-primary/20 bg-secondary">
                <span className="font-serif italic text-lg">
                  {uiStrings.about?.imageAlt || 'Image à venir'}
                </span>
              </div>
            )}
          </div>

          {/* Content Section */}
          <div className="flex flex-col">
            <h2 className="text-accent text-sm uppercase tracking-[0.2em] mb-2 font-semibold flex items-center gap-4">
              <span className="w-8 h-[1px] bg-accent" />
              {uiStrings.about?.badge || 'Artisane'}
            </h2>

            <h1 className="text-4xl lg:text-5xl font-serif mb-6 text-primary leading-tight">
              {about.name || uiStrings.about?.defaultTitle || 'À propos'}
            </h1>

            <RichText 
              content={about.bio} 
              className="prose prose-lg text-primary/80 font-light leading-relaxed mb-4 md:mb-6 max-w-none"
            />

            <div className="border-t border-primary/10 pt-4 md:pt-6 mt-4 md:mt-6 bg-primary/5 p-4 md:p-6 rounded-sm">
              <h4 className="font-serif text-2xl italic text-primary mb-4 flex items-center gap-3">
                <span className="w-6 h-[1px] bg-accent" />
                <span>{uiStrings.common?.contactTitle || 'Me contacter'}</span>
              </h4>

              <div className="flex flex-col gap-4">
                <a 
                  href={`mailto:${about.contactEmail}`}
                  className="group flex items-center gap-4 text-primary/80 hover:text-accent transition-all duration-300"
                >
                  <div className="w-10 h-10 rounded-full border border-primary/20 flex items-center justify-center group-hover:border-accent group-hover:bg-accent/5 transition-colors">
                    <Mail className="h-4 w-4" />
                  </div>
                  <span className="font-medium tracking-wide text-lg pb-0.5 border-b border-transparent group-hover:border-accent">
                    {about.contactEmail}
                  </span>
                </a>

                {about.socialLinks && about.socialLinks.length > 0 && (
                  <div className="flex flex-wrap gap-4 mt-2">
                    {about.socialLinks.map((social) => (
                      <a 
                        key={social.platform} 
                        href={social.url} 
                        target="_blank"
                        rel="noopener noreferrer"
                        className="group flex items-center gap-3 px-5 py-3 bg-secondary/50 backdrop-blur-sm border border-primary/10 rounded-sm hover:border-accent/50 hover:shadow-md transition-all duration-300 transform hover:-translate-y-0.5"
                      >
                        {social.platform.toLowerCase().includes('instagram') ? (
                          <Instagram className="h-5 w-5 text-accent" />
                        ) : social.platform.toLowerCase().includes('facebook') ? (
                          <Facebook className="h-5 w-5 text-accent" />
                        ) : (
                          <LinkIcon className="h-5 w-5 text-accent" />
                        )}
                        <span className="uppercase text-xs font-bold tracking-widest text-primary/80 group-hover:text-primary">
                          {social.platform}
                        </span>
                      </a>
                    ))}
                  </div>
                )}
              </div>
            </div>
          </div>
        </div>
      </main>

      <Footer 
        copyright={uiStrings.common?.footerCopyright || '© Mama Couture'}
        adminAccess={uiStrings.common?.adminAccess || 'Administration'}
      />
    </div>
  )
}
